name: putty-site-sync

on:
  workflow_dispatch:

env:
  TZ: "Asia/Tokyo"

jobs:
  putty-sync:
    name: PuTTY site sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir -p site
      - name: fetch from R2
        uses: andreiio/rclone-action@v1
        with:
          args: sync r2:putty/ ./site/ -v
        env: &rclone-env
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          RCLONE_CONFIG_R2_ACL: private
      - name: use rsync
        uses: GuillaumeFalourd/setup-rsync@v1.1
      - name: rsync putty site
        run: | 
          rsync -auH "${PUTTY_URL}" ./site/
          rsync -au ./putty-sync/html/ ./site/
        env:
          PUTTY_URL: ${{ secrets.PUTTY_URL }}
      - name: deproy to R2
        uses: andreiio/rclone-action@v1
        with:
          args: sync ./site/ r2:putty/ -v
        env:
          <<: *rclone-env

