name: putty-site-sync

on:
  schedule:
    - cron: '10 4 * * *'
  workflow_dispatch:

env:
  TZ: "Asia/Tokyo"

jobs:
  putty-site-sync:
    name: PuTTY site sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Site files
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/site
          key: putty-site
      - run: mkdir -p ./site
      - name: use rsync
        uses: GuillaumeFalourd/setup-rsync@v1.1
      - name: rsync putty site
        run: | 
          rsync -auH --no-perms --no-owner --omit-dir-times "${PUTTY_URL}" ./site/
          rsync -au --no-perms --no-owner --omit-dir-times ./putty-sync/html/ ./site/
        env:
          PUTTY_URL: ${{ secrets.PUTTY_URL }}
      - name: deproy to R2
        uses: andreiio/rclone-action@v1
        with:
          args: sync ./site/ r2:putty/ -v
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          RCLONE_CONFIG_R2_ACL: private
